Make Supply chain work on DAML Hub
digital-asset/ex-supply-chain pull request #97
Opened 2021-01-11 06:31 UTC by gaborh-da

2021-01-11 08:51 UTC, tamaskalcza-da requested changes

2021-01-11 08:51 UTC, tamaskalcza-da commented on Makefile
> +MAIN_DAR=target/supplychain.dar
Minor, however I think it's better:
```suggestion
MODELS_DAR=target/supplychain.dar
```

2021-01-11 08:51 UTC, tamaskalcza-da commented on Makefile
> +TRIGGERS_DAR=target/triggers.dar
```suggestion
TRIGGERS_DAR=target/triggers.dar daml.yaml
```

2021-01-11 08:51 UTC, tamaskalcza-da commented on triggers.Dockerfile
> +RUN mkdir target
Running `daml build` creates intermediary directories.
```suggestion
```

2021-01-11 08:51 UTC, tamaskalcza-da commented on triggers.Dockerfile
> +RUN daml build --project-root triggers --output /home/daml/target/triggers.dar
The working directory has already been set to `/home/daml`. Frankly, I would rather drop `target` as well, to simplify things, as in `ui.Dockerfile`.
```suggestion
RUN daml build --output target/supplychain.dar
RUN daml build --project-root triggers --output target/triggers.dar
```

2021-01-11 09:13 UTC, richardkapolnai-da commented on Makefile
> +TRIGGERS_DAR=target/triggers.dar
What would you like to achieve with this?
This change would make some confusion because we use `$(TRIGGERS_DAR)` as a target in line 20 below.

2021-01-11 09:14 UTC, richardkapolnai-da commented on Makefile
> +$(TRIGGERS_DAR): $(TRIGGERS_DAML_SRC) triggers/daml.yaml
```suggestion
$(TRIGGERS_DAR): $(TRIGGERS_DAML_SRC) triggers/daml.yaml $(MAIN_DAR)
```

2021-01-11 09:23 UTC, gaborh-da commented on triggers.Dockerfile
> +RUN daml build --project-root triggers --output /home/daml/target/triggers.dar
Relative path is calculated from the project root, that is my experience.

2021-01-11 09:26 UTC, gaborh-da commented on Makefile
> +TRIGGERS_DAR=target/triggers.dar
no

2021-01-11 09:26 UTC, gaborh-da commented on Makefile
> +MAIN_DAR=target/supplychain.dar
ok

2021-01-11 12:10 UTC, richardkapolnai-da commented on ui/src/pages/login/Login.tsx
> +                       [<MenuItem value={"Buyer"}>Buyer</MenuItem>,
you probably need the `key`s, right?

2021-01-12 10:06 UTC, tamaskalcza-da approved these changes

2021-01-12 10:07 UTC, merged